language: c
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls
install:
  - ./install-deps
before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - export LDFLAGS=-L/usr/local/lib
  - export CFLAGS=-I/usr/local/include
script:
  - ./configure --enable-gcov
  - make check
