#!/bin/sh

cd /tmp

sudo apt-get -y install libconfig-dev check libc-ares-dev

# mosquitto
git clone http://git.eclipse.org/gitroot/mosquitto/org.eclipse.mosquitto.git
cd org.eclipse.mosquitto/lib
make
sudo make install

# wiringPI
git clone git://git.drogon.net/wiringPi
cd wiringPi
./build
sudo ldconfig

./build

# to debug
ls /usr/local/lib
